dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -n base -c defaults conda
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n paramtools-dev python=$TRAVIS_PYTHON_VERSION;
  - conda env update -f environment.yml
  - conda activate paramtools-dev
  - pip install -e .

# command to run tests
script:
  - pytest -v