site_name: ParamTools Docs
nav:
    - Home: index.md
    - Parameters: parameters.md
    - API:
        - Guide: 'api/guide.md'
        - Extend: 'api/extend.md'
        - Extend with Indexing: 'api/indexing.md'

theme: mkdocs