package:
  name: paramtools
  version: 0.0.0

requirements:
  build:
    - python
    - "marshmallow>=3.0.0rc4"
    - "numpy>=1.13"
    - "python-dateutil>=2.8.0"

  run:
    - python
    - "marshmallow>=3.0.0rc4"
    - "numpy>=1.13"
    - "python-dateutil>=2.8.0"

test:
  imports:
    - paramtools

about:
  home: https://github.com/PSLmodels/ParamTools
